In [1]:
import pickle
with open('1800train_100dev_100test.source_sentence_transformer.pkl', 'rb') as f:
    train = pickle.load(f)

import numpy as np
length = []
for i in range(0, len(train)):
    length.append(len(train[i]))

X = []
for i in range(0, len(train)):
    for j in range(0, len(train[i])):
        X.append(np.array(train[i][j]))

In [2]:
from hmmlearn import hmm
remodel = hmm.GaussianHMM(n_components=4, n_iter = 50, covariance_type = 'diag', verbose = True, init_params="cm", params="cmts")
remodel.startprob_ = np.array([1, 0.0, 0.0, 0.0])
remodel.transmat_ = np.array([
                 [0.33, 0.34, 0.33, 0],
                 [0.0, 0.33, 0.34, 0.33],
                 [0.0, 0.0, 0.5, 0.5],
                 [0.0, 0.0, 0.0, 1.0]]
                            )

In [3]:
remodel.startprob_

array([1., 0., 0., 0.])

In [4]:
remodel.transmat_

array([[0.33, 0.34, 0.33, 0.  ],
       [0.  , 0.33, 0.34, 0.33],
       [0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ]])

In [5]:
remodel.fit(X, length)

         1    -6089416.4417             +nan
         2    -5946378.6559     +143037.7859
         3    -5936603.3922       +9775.2637
         4    -5930675.5218       +5927.8704
         5    -5924419.8519       +6255.6699
         6    -5919046.1805       +5373.6714
         7    -5914186.6791       +4859.5014
         8    -5910652.5028       +3534.1763
         9    -5908166.9754       +2485.5274
        10    -5906612.8555       +1554.1199
        11    -5905292.6250       +1320.2305
        12    -5904127.6612       +1164.9638
        13    -5903436.6022        +691.0590
        14    -5902984.1163        +452.4859
        15    -5902576.1048        +408.0115
        16    -5902247.3980        +328.7068
        17    -5901943.7126        +303.6854
        18    -5901795.5284        +148.1842
        19    -5901724.4619         +71.0665
        20    -5901673.7484         +50.7135
        21    -5901632.2682         +41.4801
        22    -5901616.0650         +16.2033
        23

GaussianHMM(init_params='cm', n_components=4, n_iter=50, params='cmts',
            verbose=True)

In [6]:
remodel.transmat_

array([[0.64347263, 0.26693216, 0.08959521, 0.        ],
       [0.        , 0.74953593, 0.08629852, 0.16416555],
       [0.        , 0.        , 0.36735288, 0.63264712],
       [0.        , 0.        , 0.        , 1.        ]])

In [7]:
remodel.startprob_

array([1., 0., 0., 0.])

In [8]:
def encode_convs(profix):
    sent_label = []
    with open(profix + '_sentence_transformer.pkl', 'rb') as f:
        data = pickle.load(f)
    for i in range(0, len(data)):
        labels = remodel.decode(np.array(data[i]))[1]
        sent_label.append(labels)
    
    with open(profix + '_sent_trans_cons_label.pkl', 'wb') as f:
        pickle.dump(sent_label, f)
    return sent_label

In [9]:
l = encode_convs('1800train_100dev_100test.source')